version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "3333:3333"
    env_file:
      - ./apps/auth-service/.env
    depends_on:
      - mongo
  api-gateway:
    image: devopsfaith/krakend:latest
    command: run -dc /etc/krakend/krakend.json
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./apps/api-gateway/src:/etc/krakend
