version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    env_file:
      - ./apps/auth-service/.env
    depends_on:
      - mongo
  todo-service:
    image: todo-service:latest
    container_name: todo-service
    env_file:
      - ./apps/todo-service/.env
    depends_on:
      - mongo
  backend-for-frontend:
    image: devopsfaith/krakend:2.9.1
    command: run -dc /etc/krakend/krakend.json
    container_name: backend-for-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./apps/backend-for-frontend/src:/etc/krakend
  api-gateway:
    image: devopsfaith/krakend:2.9.1
    command: run -dc /etc/krakend/krakend.json
    container_name: api-gateway
    ports:
      - "8081:8080"
    volumes:
      - ./apps/api-gateway/src/krakend.json:/etc/krakend/krakend.json
      - ./apps/api-gateway/dist/plugins:/etc/krakend/plugins
      - ./apps/api-gateway/src/assets:/etc/krakend/assets
